import Head from "next/head";
import { createClient } from "next-sanity";
import Image from "next/image";
import imageUrlBuilder from '@sanity/image-url'

const client = createClient({
  projectId: "tf7pn90e",
  dataset: "production",
});

const builder = imageUrlBuilder(client)

function urlFor(source) {
  return builder.image(source)
}

export async function getStaticProps() {
  const data = await client.fetch(
    '*[_type == "product"]{_id, name, images, slug }'
  );

  console.log({ data });
  return {
    // these props will be passed to the page
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Pulpy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-rose-50">
        {data.map((item) => {
          return (
            <div key={item._id}>
              {item.images.map((image) => {
                return (
                  <div key={image._key} className="relative aspect-square w-96">
                    <Image src={urlFor(image).width(384).height(384).url()} alt={image.caption} fill={true} className="object-contain" />
                  </div>
                );
              })}
            </div>
          );
        })}
      </main>
    </>
  );
}
