import Head from "next/head";
import { createClient } from "next-sanity";

const client = createClient({
  projectId: "tf7pn90e",
  dataset: "production",
});

export async function getStaticProps() {
  return {
    // these props will be passed to the page
    props: {},
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Pulpy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-rose-50">Howdy</main>
    </>
  );
}
